// examples/react/src/components/Report/LatestReportPanel.tsx
import { Broadcast } from "@phosphor-icons/react";
import type React from "react";

import { formatAccount } from "examples/shared/ledger/formatting/formatAccount";
import { formatClockTime } from "examples/shared/ledger/formatting/formatClockTime";
import { formatShortId } from "examples/shared/ledger/formatting/formatShortId";
import type { LedgerRuntime } from "examples/shared/ledger/types/LedgerRuntime";
import { ReceiptStateBadge } from "src/components/Badge/ReceiptStateBadge";
import { EmptyState } from "src/components/EmptyState/EmptyState";
import { Panel } from "src/components/Panel/Panel";
import { ReportDetails } from "src/components/Report/ReportDetails";
import { useEventLog } from "src/hooks/useEventLog";

type LatestReportPanelProps = { runtime: LedgerRuntime };

const LatestReport: React.FunctionComponent<LatestReportPanelProps> = ({
  runtime,
}) => {
  const [latest] = useEventLog(runtime.receipts);

  // The console destination sees every report, which is how its payload is known here.
  useEventLog(runtime.consoleLines);

  if (latest === undefined) {
    return (
      <EmptyState
        icon={Broadcast}
        title="Nothing reported yet"
        description="Press any button in Ledger. Each one fails on purpose, and its report lands here."
      />
    );
  }

  // Keyed by the report, so each new one mounts afresh and flashes.
  return (
    <div
      key={latest.receipt.id}
      className="-m-2 flex animate-flash flex-col gap-4 rounded-xl p-2 motion-reduce:animate-none"
    >
      <div className="flex flex-col gap-1">
        <div className="flex flex-wrap items-center gap-2">
          <p className="text-lg font-semibold tracking-tight">
            {latest.action}
          </p>
          <ReceiptStateBadge receipt={latest.receipt} />
        </div>
        <p className="text-sm text-stone-500">
          {formatAccount(latest.account)} · {formatClockTime(latest.at)} ·{" "}
          <span className="font-mono">{formatShortId(latest.receipt.id)}</span>
        </p>
      </div>
      <ReportDetails
        receipt={latest.receipt}
        report={runtime.findReport(latest.receipt.id)}
      />
    </div>
  );
};

export const LatestReportPanel: React.FunctionComponent<
  LatestReportPanelProps
> = ({ runtime }) => (
  <Panel
    title="Latest report"
    icon={Broadcast}
    shows="Where the last thing you did went: every destination, what it answered, and why."
    aside={null}
  >
    <LatestReport runtime={runtime} />
  </Panel>
);

// examples/svelte/src/components/Report/LatestReportPanel.svelte
<script lang="ts">
  import type { LedgerRuntime } from "examples/shared/ledger/types/LedgerRuntime";
  import { ICONS } from "examples/shared/ui/constants/icons";
  import { CARD_CLASS_NAME } from "examples/shared/ui/styles/cardStyles";
  import EmptyState from "src/components/EmptyState/EmptyState.svelte";
  import IconTile from "src/components/IconTile/IconTile.svelte";
  import ReportDetails from "src/components/Report/ReportDetails.svelte";
  import { useExternalStore } from "src/utilities/useExternalStore";

  type Props = { runtime: LedgerRuntime };

  let { runtime }: Props = $props();

  const receipts = useExternalStore(
    (listener) => runtime.receipts.subscribe(listener),
    () => runtime.receipts.getSnapshot(),
  );

  const latest = $derived(receipts.current[0]);
</script>

<section
  aria-label="Latest report"
  class={["flex h-full min-w-0 flex-col gap-4 p-5", CARD_CLASS_NAME]}
>
  <header class="flex flex-col gap-1.5">
    <div class="flex flex-wrap items-center gap-2">
      <IconTile icon={ICONS.broadcast} size="small" />
      <h3
        class="text-base font-semibold tracking-tight text-stone-800 dark:text-stone-200"
      >
        Latest report
      </h3>
    </div>
    <p class="text-sm text-stone-500 dark:text-stone-400">
      Where the last thing you did went: every destination, what it answered,
      and why.
    </p>
  </header>
  {#if latest === undefined}
    <EmptyState
      icon={ICONS.broadcast}
      title="Nothing reported yet"
      description="Press any button in Ledger. Each one fails on purpose, and its report lands here."
    />
  {:else}
    <!-- Keyed by the report, so each new one mounts afresh and flashes. -->
    {#key latest.receipt.id}
      <ReportDetails tracked={latest} />
    {/key}
  {/if}
</section>
