// packages/react/src/context/FlareProvider.tsx
import type { PropsWithChildren } from "react";

import { FlareContext } from "src/context/FlareContext";
import type { RegisteredFlare } from "src/types/Register";

export type FlareProviderProps = PropsWithChildren<{
  flare: RegisteredFlare;
}>;

/**
 * Publishes one Flare to the tree below, and does nothing else. The Flare
 * owns its own lifetime: whoever constructed it starts it and disposes it, so
 * mounting the provider starts no destination and unmounting it shuts none
 * down, not even an SDK Flare owns.
 *
 * @example
 * ```tsx
 * const flare = new Flare({ destinations: { sentry: sentry({ sdk: Sentry }) } });
 * flare.start();
 *
 * <FlareProvider flare={flare}>
 *   <Application />
 * </FlareProvider>
 * ```
 */
export const FlareProvider = ({ flare, children }: FlareProviderProps) => (
  <FlareContext.Provider value={flare}>{children}</FlareContext.Provider>
);

// packages/solid/src/context/FlareProvider.ts
import { createComponent, createMemo } from "solid-js";
import type { ParentProps } from "solid-js";

import { FlareContext } from "src/context/FlareContext";
import type { RegisteredFlare } from "src/types/Register";

export type FlareProviderProps = ParentProps<{
  flare: RegisteredFlare;
}>;

/**
 * Publishes one Flare to the components below, and does nothing else. The
 * Flare owns its own lifetime: whoever constructed it starts it and disposes
 * it, so mounting the provider starts no destination and unmounting it shuts
 * none down, not even an SDK Flare owns.
 *
 * @example
 * ```tsx
 * <FlareProvider flare={flare}>
 *   <Application />
 * </FlareProvider>
 * ```
 */
export const FlareProvider = (props: FlareProviderProps) =>
  createComponent(FlareContext.Provider, {
    value: createMemo(() => props.flare),
    get children() {
      return props.children;
    },
  });
