// examples/react/src/Application.tsx
import type { Receipt } from "@priemskiyyy/flare";
import { FlareDevtools } from "@priemskiyyy/flare-devtools/react";
import { FlareProvider } from "@priemskiyyy/flare-react";
import type React from "react";
import { useEffect, useState } from "react";

import { INITIAL_ACCOUNT } from "examples/shared/ledger/constants/accounts";
import { createLedgerRuntime } from "examples/shared/ledger/reporting/createLedgerRuntime";
import type { AccountId } from "examples/shared/ledger/types/AccountId";
import type { LedgerDestination } from "examples/shared/ledger/types/LedgerDestination";
import type { LedgerRuntime } from "examples/shared/ledger/types/LedgerRuntime";
import type { ReportBackend } from "examples/shared/ledger/types/ReportBackend";
import type { SimulatedProviders } from "examples/shared/ledger/types/SimulatedProviders";
import { switchAccount } from "examples/shared/ledger/utils/switchAccount";
import { DestinationsPanel } from "src/components/Destinations/DestinationsPanel";
import { Footer } from "src/components/Footer/Footer";
import { Header } from "src/components/Header/Header";
import { Hero } from "src/components/Hero/Hero";
import { LabPanel } from "src/components/Lab/LabPanel";
import { NetworkPanel } from "src/components/Lab/NetworkPanel";
import { LedgerApp } from "src/components/Ledger/LedgerApp";
import { ReceiptsPanel } from "src/components/Receipts/ReceiptsPanel";
import { LatestReportPanel } from "src/components/Report/LatestReportPanel";
import { Section } from "src/components/Section/Section";
import { TimelinePanel } from "src/components/Timeline/TimelinePanel";

type ApplicationProps = {
  backend: ReportBackend;
  providers: SimulatedProviders;
  runtime: LedgerRuntime;
};

export const Application: React.FunctionComponent<ApplicationProps> = ({
  backend,
  providers,
  runtime: initialRuntime,
}) => {
  const [account, setAccount] = useState<AccountId | null>(INITIAL_ACCOUNT);
  const [runtime, setRuntime] = useState(initialRuntime);

  // A page that is being hidden may never come back: send what is queued.
  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.visibilityState !== "hidden") {
        return;
      }

      runtime.flare.flush({ timeout: 1_000 }).catch(() => {});
    };

    document.addEventListener("visibilitychange", handleVisibilityChange);

    return () => {
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, [runtime]);

  const handleAccountSelect = (next: AccountId | null) => {
    setAccount(next);
    switchAccount(runtime.flare, providers, next);
  };

  const handleReceipt = (
    receipt: Receipt<LedgerDestination>,
    action: string,
  ) => {
    runtime.track(receipt, action, account);
  };

  // A disposed Flare cannot start again, so a restart replaces it.
  const replaceRuntime = () => {
    runtime.dispose();

    const next = createLedgerRuntime({ backend, providers });

    switchAccount(next.flare, providers, account);
    setRuntime(next);

    return next;
  };

  const handleRestartPress = () => {
    replaceRuntime().flare.start();
  };

  const handleRestartUnstartedPress = () => {
    replaceRuntime();
  };

  const handleStartPress = () => {
    runtime.flare.start();
  };

  return (
    <FlareProvider flare={runtime.flare}>
      <Header />
      <main className="mx-auto flex max-w-7xl flex-col gap-16 px-4 py-8 sm:px-6">
        <Hero />
        <Section
          id="app"
          hint="Pay INV-1042. The card is declined on purpose, and its report appears under Latest report. Then switch to Grace Hopper and pay: her report carries nothing of Ada's."
        >
          <div className="grid items-start gap-4 lg:grid-cols-2">
            <LedgerApp
              account={account}
              onAccountSelect={handleAccountSelect}
              onReceipt={handleReceipt}
            />
            <LatestReportPanel runtime={runtime} />
          </div>
        </Section>
        <Section
          id="receipts"
          hint="Attach receipt.pdf as Ada, then switch to Grace before it fails. The upload was Ada's, so Flare sends it nowhere rather than as Grace's."
        >
          <ReceiptsPanel runtime={runtime} />
        </Section>
        <Section
          id="destinations"
          hint="Press Remind Northwind. A reminder is a message, which PostHog and Datadog skip, and the customer's address arrives as [email]."
        >
          <DestinationsPanel
            runtime={runtime}
            backend={backend}
            providers={providers}
          />
        </Section>
        <Section
          id="lab"
          hint="Take your API offline, then pay an invoice. Only your API fails; Sentry and the console still get the report."
        >
          <div className="grid gap-3 xl:grid-cols-2">
            <LabPanel
              backend={backend}
              providers={providers}
              onReceipt={handleReceipt}
            />
            <NetworkPanel backend={backend} />
          </div>
        </Section>
        <Section
          id="timeline"
          hint="Press Restart without starting, pay, then press Start. The report waited in the buffer and went out once Flare started."
        >
          <TimelinePanel
            runtime={runtime}
            onRestartPress={handleRestartPress}
            onRestartUnstartedPress={handleRestartUnstartedPress}
            onStartPress={handleStartPress}
          />
        </Section>
      </main>
      <Footer />
      <FlareDevtools />
    </FlareProvider>
  );
};

// examples/solid/src/Application.tsx
import type { Receipt } from "@priemskiyyy/flare";
import { FlareDevtools } from "@priemskiyyy/flare-devtools/solid";
import { FlareProvider } from "@priemskiyyy/flare-solid";
import { createSignal, onCleanup } from "solid-js";
import type { Component } from "solid-js";

import { INITIAL_ACCOUNT } from "examples/shared/ledger/constants/accounts";
import type { AccountId } from "examples/shared/ledger/types/AccountId";
import type { LedgerDestination } from "examples/shared/ledger/types/LedgerDestination";
import type { LedgerRuntime } from "examples/shared/ledger/types/LedgerRuntime";
import type { SimulatedProviders } from "examples/shared/ledger/types/SimulatedProviders";
import { switchAccount } from "examples/shared/ledger/utils/switchAccount";
import { Header } from "src/components/Header/Header";
import { LedgerApp } from "src/components/Ledger/LedgerApp";
import { LatestReportPanel } from "src/components/Report/LatestReportPanel";

type ApplicationProps = {
  runtime: LedgerRuntime;
  providers: SimulatedProviders;
};

export const Application: Component<ApplicationProps> = (props) => {
  const [account, setAccount] = createSignal<AccountId | null>(INITIAL_ACCOUNT);

  // A page that is being hidden may never come back: send what is queued.
  const handleVisibilityChange = () => {
    if (document.visibilityState !== "hidden") {
      return;
    }

    props.runtime.flare.flush({ timeout: 1_000 }).catch(() => {});
  };

  document.addEventListener("visibilitychange", handleVisibilityChange);
  onCleanup(() => {
    document.removeEventListener("visibilitychange", handleVisibilityChange);
  });

  const handleAccountSelect = (next: AccountId | null) => {
    setAccount(next);
    switchAccount(props.runtime.flare, props.providers, next);
  };

  const handleReceipt = (
    receipt: Receipt<LedgerDestination>,
    action: string,
  ) => {
    props.runtime.track(receipt, action, account());
  };

  return (
    <FlareProvider flare={props.runtime.flare}>
      <Header />
      <main class="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-8 sm:px-6">
        <div class="flex max-w-3xl flex-col gap-2">
          <h2 class="text-2xl font-semibold tracking-tight sm:text-3xl">
            Ledger on Solid
          </h2>
          <p class="text-base leading-relaxed text-stone-600 dark:text-stone-400">
            The invoicing app from the React example, written with Solid
            accessors. Every button fails on purpose, and its report lands under
            Latest report with what each destination answered. The Flare button
            in the corner opens the devtools over the same runtime.
          </p>
        </div>
        <div class="grid items-start gap-4 lg:grid-cols-2">
          <LedgerApp
            account={account()}
            onAccountSelect={handleAccountSelect}
            onReceipt={handleReceipt}
          />
          <LatestReportPanel runtime={props.runtime} />
        </div>
      </main>
      <FlareDevtools />
    </FlareProvider>
  );
};
