// examples/react/src/components/Ledger/InvoiceRow.tsx
import { CreditCard, PaperPlaneTilt } from "@phosphor-icons/react";
import type { Receipt } from "@priemskiyyy/flare";
import { useFlare } from "@priemskiyyy/flare-react";
import type React from "react";

import { formatMoney } from "examples/shared/ledger/formatting/formatMoney";
import type { Invoice } from "examples/shared/ledger/types/Invoice";
import type { LedgerDestination } from "examples/shared/ledger/types/LedgerDestination";
import { PaymentDeclinedError } from "examples/shared/ledger/utils/PaymentDeclinedError";
import { buttonStyles } from "examples/shared/ui/styles/buttonStyles";

type InvoiceRowProps = {
  invoice: Invoice;
  onReceipt: (receipt: Receipt<LedgerDestination>, action: string) => void;
};

export const InvoiceRow: React.FunctionComponent<InvoiceRowProps> = ({
  invoice,
  onReceipt,
}) => {
  const flare = useFlare();

  const handlePayPress = () => {
    flare.breadcrumb("invoiceOpened", { invoice: invoice.id });

    const receipt = flare.capture(
      new PaymentDeclinedError(`The card for ${invoice.id} was declined`),
      {
        tags: { area: "billing" },
        contexts: {
          payment: {
            invoice: invoice.id,
            amount: invoice.amount,
            cardToken: "tok_live_4242",
            iban: "DE89 3704 0044 0532 0130 00",
          },
        },
      },
    );

    onReceipt(receipt, `Pay ${invoice.id}`);
  };

  const handleRemindPress = () => {
    const receipt = flare.message(
      `The reminder to ${invoice.customerEmail} bounced`,
      { level: "warning", tags: { area: "reminders" } },
    );

    onReceipt(receipt, `Remind ${invoice.customer}`);
  };

  return (
    <li className="flex flex-wrap items-center gap-3 px-4 py-3">
      <span className="flex min-w-0 flex-1 flex-col">
        <span className="truncate text-sm font-semibold">
          {invoice.customer}
        </span>
        <span className="truncate font-mono text-xs text-stone-500">
          {invoice.id} · due {invoice.due}
        </span>
      </span>
      <span className="font-mono text-sm tabular-nums">
        {formatMoney(invoice.amount)}
      </span>
      <div className="flex gap-2">
        <button
          type="button"
          onClick={handlePayPress}
          className={buttonStyles({ variant: "primary", size: "small" })}
        >
          <CreditCard aria-hidden="true" size={14} weight="bold" />
          Pay {invoice.id}
        </button>
        <button
          type="button"
          onClick={handleRemindPress}
          className={buttonStyles({ size: "small" })}
        >
          <PaperPlaneTilt aria-hidden="true" size={14} weight="bold" />
          Remind {invoice.customer}
        </button>
      </div>
    </li>
  );
};

// examples/solid/src/components/Ledger/InvoiceRow.tsx
import type { Receipt } from "@priemskiyyy/flare";
import { useFlare } from "@priemskiyyy/flare-solid";
import type { Component } from "solid-js";

import { formatMoney } from "examples/shared/ledger/formatting/formatMoney";
import type { Invoice } from "examples/shared/ledger/types/Invoice";
import type { LedgerDestination } from "examples/shared/ledger/types/LedgerDestination";
import { PaymentDeclinedError } from "examples/shared/ledger/utils/PaymentDeclinedError";
import { ICONS } from "examples/shared/ui/constants/icons";
import { buttonStyles } from "examples/shared/ui/styles/buttonStyles";
import { BaseIcon } from "src/components/BaseIcon/BaseIcon";

type InvoiceRowProps = {
  invoice: Invoice;
  onReceipt: (receipt: Receipt<LedgerDestination>, action: string) => void;
};

export const InvoiceRow: Component<InvoiceRowProps> = (props) => {
  const flare = useFlare();

  const handlePayPress = () => {
    const { invoice } = props;

    flare().breadcrumb("invoiceOpened", { invoice: invoice.id });

    const receipt = flare().capture(
      new PaymentDeclinedError(`The card for ${invoice.id} was declined`),
      {
        tags: { area: "billing" },
        contexts: {
          payment: {
            invoice: invoice.id,
            amount: invoice.amount,
            cardToken: "tok_live_4242",
            iban: "DE89 3704 0044 0532 0130 00",
          },
        },
      },
    );

    props.onReceipt(receipt, `Pay ${invoice.id}`);
  };

  const handleRemindPress = () => {
    const { invoice } = props;

    const receipt = flare().message(
      `The reminder to ${invoice.customerEmail} bounced`,
      { level: "warning", tags: { area: "reminders" } },
    );

    props.onReceipt(receipt, `Remind ${invoice.customer}`);
  };

  return (
    <li class="flex flex-wrap items-center gap-3 px-4 py-3">
      <span class="flex min-w-0 flex-1 flex-col">
        <span class="truncate text-sm font-semibold">
          {props.invoice.customer}
        </span>
        <span class="truncate font-mono text-xs text-stone-500">
          {props.invoice.id} · due {props.invoice.due}
        </span>
      </span>
      <span class="font-mono text-sm tabular-nums">
        {formatMoney(props.invoice.amount)}
      </span>
      <div class="flex gap-2">
        <button
          type="button"
          onClick={handlePayPress}
          class={buttonStyles({ variant: "primary", size: "small" })}
        >
          <BaseIcon src={ICONS.creditCard} size="small" />
          Pay {props.invoice.id}
        </button>
        <button
          type="button"
          onClick={handleRemindPress}
          class={buttonStyles({ size: "small" })}
        >
          <BaseIcon src={ICONS.paperPlaneTilt} size="small" />
          Remind {props.invoice.customer}
        </button>
      </div>
    </li>
  );
};
