// packages/react/src/components/FlareErrorBoundary.tsx
import type { CaptureOptions, Receipt } from "@priemskiyyy/flare";
import { Component } from "react";
import type { ErrorInfo, PropsWithChildren, ReactNode } from "react";

import { FlareContext } from "src/context/FlareContext";
import type {
  RegisteredDestinationName,
  RegisteredSchema,
} from "src/types/Register";

type Caught = { error: unknown };

export type FlareErrorBoundaryProps = PropsWithChildren<{
  /** What to render instead of the children, or a function that also receives the error and a reset. */
  fallback:
    ReactNode | ((props: { error: unknown; reset: () => void }) => ReactNode);
  /** Options for the report the boundary makes, such as tags, a level or `to`. */
  capture?: CaptureOptions<RegisteredDestinationName, RegisteredSchema>;
  /** Told after the report is made. */
  onError?: (caught: {
    error: unknown;
    receipt: Receipt<RegisteredDestinationName>;
  }) => void;
}>;

/**
 * Reports an error thrown while rendering the tree below it, and renders a
 * fallback. The component stack travels as the `react` context; with a typed
 * schema, declare that context or it is dropped and recorded as a loss.
 *
 * Like every React error boundary it sees only errors thrown during
 * rendering, in lifecycle methods and in constructors. It does not see errors
 * in event handlers, in asynchronous code, during server rendering, or in the
 * boundary itself: report those with `flare.capture`.
 *
 * @example
 * ```tsx
 * <FlareErrorBoundary fallback={<p>Something went wrong.</p>} capture={{ tags: { area: "cart" } }}>
 *   <Cart />
 * </FlareErrorBoundary>
 * ```
 */
export class FlareErrorBoundary extends Component<
  FlareErrorBoundaryProps,
  { caught: Caught | null }
> {
  static override contextType = FlareContext;

  declare context: React.ContextType<typeof FlareContext>;

  override state: { caught: Caught | null } = { caught: null };

  static getDerivedStateFromError(error: unknown) {
    return { caught: { error } };
  }

  override componentDidCatch(error: unknown, info: ErrorInfo) {
    const flare = this.context;
    if (flare === undefined) {
      return;
    }

    const { capture, onError } = this.props;
    const receipt = flare.capture(error, {
      ...capture,
      contexts: {
        ...capture?.contexts,
        react: { componentStack: info.componentStack ?? "" },
      },
    });

    if (typeof onError !== "function") {
      return;
    }
    onError({ error, receipt });
  }

  handleReset = () => {
    this.setState({ caught: null });
  };

  override render() {
    if (this.context === undefined) {
      throw new Error(
        "FlareErrorBoundary must be used within a FlareProvider.",
      );
    }

    const { caught } = this.state;
    if (caught === null) {
      return this.props.children;
    }

    const { fallback } = this.props;
    if (typeof fallback !== "function") {
      return fallback;
    }
    return fallback({ error: caught.error, reset: this.handleReset });
  }
}

// packages/solid/src/components/FlareErrorBoundary.ts
import type { CaptureOptions, Receipt } from "@priemskiyyy/flare";
import { ErrorBoundary, createComponent } from "solid-js";
import type { JSX, ParentProps } from "solid-js";

import { useFlareContext } from "src/primitives/internal/useFlareContext";
import type {
  RegisteredDestinationName,
  RegisteredSchema,
} from "src/types/Register";

export type FlareErrorBoundaryProps = ParentProps<{
  /** What to render instead of the children, or a function that also receives the error and a reset. */
  fallback:
    | JSX.Element
    | ((props: { error: unknown; reset: () => void }) => JSX.Element);
  /** Options for the report the boundary makes, such as tags, a level or `to`. */
  capture?: CaptureOptions<RegisteredDestinationName, RegisteredSchema>;
  /** Told after the report is made. */
  onError?: (caught: {
    error: unknown;
    receipt: Receipt<RegisteredDestinationName>;
  }) => void;
}>;

/**
 * Reports an error caught by Solid's `ErrorBoundary` in the tree below it, and
 * renders a fallback. Solid has no component stack, so the report carries only
 * what `capture` gives it.
 *
 * Like every Solid error boundary it sees errors thrown while rendering and
 * inside reactive computations. It does not see errors in event handlers or in
 * asynchronous code outside a computation: report those with `flare().capture`.
 *
 * @example
 * ```tsx
 * <FlareErrorBoundary fallback={<p>Something went wrong.</p>} capture={{ tags: { area: "cart" } }}>
 *   <Cart />
 * </FlareErrorBoundary>
 * ```
 */
export const FlareErrorBoundary = (props: FlareErrorBoundaryProps) => {
  const flare = useFlareContext("FlareErrorBoundary");

  // Solid calls this once for each error it catches, which is when to report.
  // It calls it untracked, but only because it declares parameters: a fallback
  // function that declares none is rendered as a value instead.
  const handleError = (error: unknown, reset: () => void) => {
    const { capture, onError, fallback } = props;
    const receipt = flare().capture(error, capture);

    if (typeof onError === "function") {
      onError({ error, receipt });
    }

    if (typeof fallback !== "function") {
      return fallback;
    }

    return fallback({ error, reset });
  };

  return createComponent(ErrorBoundary, {
    fallback: handleError,
    get children() {
      return props.children;
    },
  });
};
